In [7]:
import numpy as np



In [10]:
np_weekly_hrs[np_weekly_hrs>40]

array([41, 55, 47])

In [9]:
np_weekly_hrs = np.array([23,41,55,47,38])

In [11]:
np_weekly_hrs[np_weekly_hrs!=40]

array([23, 41, 55, 47, 38])

In [12]:
np.logical_and(np_weekly_hrs>20,np_weekly_hrs<50)

array([ True,  True, False,  True,  True])

In [13]:
np.logical_not(np_weekly_hrs>35)

array([ True, False, False, False, False])

In [14]:
cyclist_trials = np.array([[10,15,17,26],[12,11,21,24]])

In [15]:
first_trial = cyclist_trials[0]

In [16]:
first_trial

array([10, 15, 17, 26])

In [17]:
second_trial = cyclist_trials[1]

In [19]:
second_trial

array([12, 11, 21, 24])

In [20]:
first_cyclist_firstTrial = cyclist_trials[0][0]
first_cyclist_firstTrial

10

In [21]:
first_cyclist_all_trials = cyclist_trials[:,0]

In [22]:
first_cyclist_all_trials

array([10, 12])

In [24]:
cyclist_trials.shape

(2, 4)

In [25]:
two_cyclist_trial_data=cyclist_trials[:,1:3]

In [26]:
two_cyclist_trial_data

array([[15, 17],
       [11, 21]])

In [27]:
for iterate_cyclist_trials_data in cyclist_trials:
    print(iterate_cyclist_trials_data)

[10 15 17 26]
[12 11 21 24]


In [29]:
for iterate_two_cyclist_trial_data in two_cyclist_trial_data:
    print(iterate_two_cyclist_trial_data)

[15 17]
[11 21]


In [30]:
test_scores = np.array([[83,71,57,63],[54,68,81,45]])

In [33]:
passing_score = test_scores>60

In [34]:
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [35]:
test_scores[passing_score]

array([83, 71, 63, 68, 81])

In [42]:
boroughs_in_NYC = np.array(['Manhatten', 'Bronx', 'Brooklyn'])
View_of_Borough_in_NYC = boroughs_in_NYC.view()

In [43]:
len(View_of_Borough_in_NYC)

3

In [44]:
View_of_Borough_in_NYC[4] = 'Central Olga'

IndexError: index 4 is out of bounds for axis 0 with size 3

In [45]:
np_sqrt = np.sqrt([2,4,9,16])
np_sqrt

array([1.41421356, 2.        , 3.        , 4.        ])

In [46]:
from numpy import pi
np.cos(0)

1.0

In [47]:
np.sin(pi/2)

1.0

In [48]:
np.cos(pi)

-1.0

In [49]:
np.floor([1.5,1.6,2.7])

array([1., 1., 2.])

In [51]:
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])

In [52]:
new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])

In [53]:
new_cyclist_trials.ravel()

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [54]:
new_cyclist_trials.reshape(3,4)

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [56]:
new_cyclist_trials.resize(2,6)

In [57]:
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [58]:
np.hsplit(new_cyclist_trials,2)

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 23]])]

In [64]:
new_cyclist_1 = np.array([[10],[15],[26],[13],[19]])

In [68]:
np.hstack((new_cyclist_1,new_cyclist_2))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 6

In [63]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [72]:
array_a = np.array([2, 3, 5, 8])
array_b = np.array([.3, .3, .3, .3])

In [73]:
array_a * array_b

array([0.6, 0.9, 1.5, 2.4])

In [74]:
scalar_c = .3

In [75]:
array_a * scalar_c

array([0.6, 0.9, 1.5, 2.4])

In [76]:
test_scores = np.array([[83,71,57,63],[54,68,81,45]])

In [77]:
test_scores.transpose()

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

In [80]:
inverse_array = np.array([[10,20],[15,25]])

In [81]:
np.linalg.inv(inverse_array)

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [82]:
trace_array = np.array([[10,20],[22,31]])

In [83]:
np.trace(trace_array)

41

In [85]:
open('downloads/Countries with GDP.txt')

<_io.TextIOWrapper name='downloads/Countries with GDP.txt' mode='r' encoding='cp1252'>

In [87]:
f = open('downloads/Countries with GDP.txt','r')

In [88]:
f

<_io.TextIOWrapper name='downloads/Countries with GDP.txt' mode='r' encoding='cp1252'>

In [89]:
f.close()

In [91]:
with open('downloads/Countries with GDP.txt') as f:
    contents = f.readlines()

In [93]:
with open('downloads/Countries with GDP.txt') as f:
    contents = f.read()
    print(contents)

List of countries:

'Algeria','Angola','Argentina','Australia','Austria','Bahamas','Bangladesh','Belarus','Belgium','Bhutan','Brazil','Bulgaria','Cambodia','Cameroon','Chile','China','Colombia','Cyprus','Denmark','El Salvador','Estonia','Ethiopia','Fiji','Finland','France','Georgia','Ghana','Grenada','Guinea','Haiti','Honduras','Hungary','India','Indonesia','Ireland','Italy','Japan','Kenya', 'South Korea','Liberia','Malaysia','Mexico', 'Morocco','Nepal','New Zealand','Norway','Pakistan', 'Peru','Qatar','Russia','Singapore','South Africa','Spain','Sweden','Switzerland','Thailand', 'United Arab Emirates','United Kingdom','United States','Uruguay','Venezuela','Vietnam','Zimbabwe'


GDP values for each country:

2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,19466.99052,588.3691778,2890.345675,24733.62696,1445.760002,4803.398244,2618.876037,590.4521124,665.7982328,7122.938458,2639.54156,3362.4656,15378.16704,30860.12808,2579.115607,6525.541272,229.6769525,2242.689259,27570.485

In [97]:
lines = []
with open('downloads/Countries with GDP.txt') as f:
    lines = f.readlines()
    
count = 0
for line in lines:
    count += 1
    print(f'line {count}: {line}')

line 1: List of countries:

line 2: 

line 3: 'Algeria','Angola','Argentina','Australia','Austria','Bahamas','Bangladesh','Belarus','Belgium','Bhutan','Brazil','Bulgaria','Cambodia','Cameroon','Chile','China','Colombia','Cyprus','Denmark','El Salvador','Estonia','Ethiopia','Fiji','Finland','France','Georgia','Ghana','Grenada','Guinea','Haiti','Honduras','Hungary','India','Indonesia','Ireland','Italy','Japan','Kenya', 'South Korea','Liberia','Malaysia','Mexico', 'Morocco','Nepal','New Zealand','Norway','Pakistan', 'Peru','Qatar','Russia','Singapore','South Africa','Spain','Sweden','Switzerland','Thailand', 'United Arab Emirates','United Kingdom','United States','Uruguay','Venezuela','Vietnam','Zimbabwe'

line 4: 

line 5: 

line 6: GDP values for each country:

line 7: 

line 8: 2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,19466.99052,588.3691778,2890.345675,24733.62696,1445.760002,4803.398244,2618.876037,590.4521124,665.7982328,7122.938458,2639.54156,3362.4656,15378.1670

In [98]:
with open('downloads/Countries with GDP.txt') as f:
    line = f.readline()
    while line:
        line = f.readline()
        print(line)



'Algeria','Angola','Argentina','Australia','Austria','Bahamas','Bangladesh','Belarus','Belgium','Bhutan','Brazil','Bulgaria','Cambodia','Cameroon','Chile','China','Colombia','Cyprus','Denmark','El Salvador','Estonia','Ethiopia','Fiji','Finland','France','Georgia','Ghana','Grenada','Guinea','Haiti','Honduras','Hungary','India','Indonesia','Ireland','Italy','Japan','Kenya', 'South Korea','Liberia','Malaysia','Mexico', 'Morocco','Nepal','New Zealand','Norway','Pakistan', 'Peru','Qatar','Russia','Singapore','South Africa','Spain','Sweden','Switzerland','Thailand', 'United Arab Emirates','United Kingdom','United States','Uruguay','Venezuela','Vietnam','Zimbabwe'





GDP values for each country:



2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,19466.99052,588.3691778,2890.345675,24733.62696,1445.760002,4803.398244,2618.876037,590.4521124,665.7982328,7122.938458,2639.54156,3362.4656,15378.16704,30860.12808,2579.115607,6525.541272,229.6769525,2242.689259,27570.4852,23016.84778

In [99]:
with open('downloads/Countries with GDP.txt') as f:
    for line in f:
        print(line)

List of countries:



'Algeria','Angola','Argentina','Australia','Austria','Bahamas','Bangladesh','Belarus','Belgium','Bhutan','Brazil','Bulgaria','Cambodia','Cameroon','Chile','China','Colombia','Cyprus','Denmark','El Salvador','Estonia','Ethiopia','Fiji','Finland','France','Georgia','Ghana','Grenada','Guinea','Haiti','Honduras','Hungary','India','Indonesia','Ireland','Italy','Japan','Kenya', 'South Korea','Liberia','Malaysia','Mexico', 'Morocco','Nepal','New Zealand','Norway','Pakistan', 'Peru','Qatar','Russia','Singapore','South Africa','Spain','Sweden','Switzerland','Thailand', 'United Arab Emirates','United Kingdom','United States','Uruguay','Venezuela','Vietnam','Zimbabwe'





GDP values for each country:



2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,19466.99052,588.3691778,2890.345675,24733.62696,1445.760002,4803.398244,2618.876037,590.4521124,665.7982328,7122.938458,2639.54156,3362.4656,15378.16704,30860.12808,2579.115607,6525.541272,229.6769525,2242.689259,27

In [100]:
line.max()

AttributeError: 'str' object has no attribute 'max'